### ISSUE TITLE
unable to download art

### ISSUE THREAD

**Issue by zaqk** [UWCS/aoko#15]
I'm unable to download album art. This is the error that I get:

ERROR VideoQueue download - Cannot download thumbnail for https://www.youtube.com/watch?v=yYXC7iZWnQI
java.net.MalformedURLException: unknown protocol: c
        at java.net.URL.<init>(URL.java:593)
        at java.net.URL.<init>(URL.java:483)
        at java.net.URL.<init>(URL.java:432)
        at uk.co.probablyfine.aoko.download.ArtDownloader.downloadFile(ArtDownloader.java:60)
        at uk.co.probablyfine.aoko.download.ArtDownloader.getYoutubeArt(ArtDownloader.java:37)
        at uk.co.probablyfine.aoko.download.VideoQueue.download(VideoQueue.java:165)
        at uk.co.probablyfine.aoko.download.VideoQueue$1.run(VideoQueue.java:69)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)

Is this a preexisting issue or is this just me?

**Comment by zaqk** [comment]
If this is actually an issue for anyone other than me accept my pull request which has a fix. The original downloadFile method wasn't specifying a proper name for the file.
